# Autogenerated wrapper script for ZoneDetect_jll for aarch64-apple-darwin
export libzonedetect

JLLWrappers.@generate_wrapper_header("ZoneDetect")
JLLWrappers.@declare_library_product(libzonedetect, "@rpath/libzonedetect.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libzonedetect,
        "lib/libzonedetect.0.0.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
