# Autogenerated wrapper script for ZoneDetect_jll for powerpc64le-linux-gnu
export libzonedetect

JLLWrappers.@generate_wrapper_header("ZoneDetect")
JLLWrappers.@declare_library_product(libzonedetect, "libzonedetect.so.0.0.0")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libzonedetect,
        "lib/libzonedetect.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
